config/routes.rb
Rails.application.routes.draw do
  get    'dashboard'           => 'dashboard#index'
  get    'join'                => 'join#new'
  post   'join'                => 'join#create'

  get    'slack'               => 'slack#new'
  post   'slack'               => 'slack#notifier'

  resources :comments, only: [:create]

  resources :request_acceptants, only: [:edit]

  get    'posts/:id/comments'  => 'posts#comments'
  resources :posts, only: [:create, :destroy]

  namespace :admin do
    get    'projects/list_users' => 'projects#list_users'
    post   'projects/add'        => 'projects#add'
    post   'projects/pdf'        => 'projects#pdf'
    delete 'projects/remove'     => 'projects#remove'
    resources :projects

    resources :requests, only: [:index, :create, :destroy]
    post 'requests/pdf'    => 'requests#pdf'
    get 'requests/sent'    => 'requests#sent'
    get 'requests/pending' => 'requests#pending'
  end

  resources :projects, only: [:index, :show]

  devise_for :users, controllers: { registrations: 'users/registrations' }

  resources :users

  authenticated :user do
    root :to => 'dashboard#index', :as => :authenticated_root
  end
  root 'homepage#index'

  match '*path', to: 'errors#routing', via: [:get]
end

app/models/project.rb
class Project < ActiveRecord::Base
  has_many :relationships, foreign_key: "project_id",
                           dependent:   :destroy

  has_many :users, through: :relationships,  source: :user
  has_many :posts, dependent: :destroy

  mount_uploader :file, FileUploader

  validates :name, presence: true
  validates :description, presence: true
end

app/controllers/admin/projects_controller.rb
class Admin::ProjectsController < Admin::ApplicationController

  def index
    @projects = Project.all
  end

  def new
    @project = Project.new
  end

  def edit
    @project = Project.find params[:id]
  end

  def update
    @project = Project.find params[:id]
    if @project.update_attributes(project_params)
      redirect_to admin_project_url(@project), notice: "Project updated!"
    else
      redirect_to admin_project_url(@project), alert: "Something wrong, please try again."
    end
  end

  def create
    @project = Project.new project_params
    if @project.save
      flash[:success] = "Request sent!"
      redirect_to root_url
    else
      render :new
    end
  end

  def show
    begin
      @project = Project.find params[:id]
      page = (params[:page] || 0).to_i
      find_users page
      respond_to do |format|
          format.html { render :show }
      end
    rescue
      redirect_to root_url
    end
  end

  def add
    user = User.find params[:user_id]
    project = Project.find params[:project_id]

    user.relationships.create project_id: project.id

    @results = project.users

    respond_to do |format|
        format.html
        format.json { render json: @results.to_json(
          include: { projects: { only: :id } }) }
    end
  end

  def remove
    user = User.find params[:user_id]
    project = Project.find params[:project_id]

    user.relationships.find_by_project_id(project.id).destroy

    @results = project.users

    respond_to do |format|
        format.html
        format.json { render json: @results.to_json(
          include: { projects: { only: :id } }) }
    end
  end

  def list_users
    project = Project.find params[:project_id]
    @results = project.users

    respond_to do |format|
        format.html
        format.json { render json: @results.to_json(
          include: { projects: { only: :id } }) }
    end
  end

  def pdf
    project = Project.find(params[:format])

    # File location
    location = project.file.file.file
    filename = "project_" + project.id.to_s + "_attachment.pdf"

    send_file(location, :filename => filename, :type => "application/pdf")
  end

  private
  def project_params
    request = params.require(:project).permit(:name, :description, :file)
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

  def index
    @projects = current_user.projects
  end

  def show
    page = (params[:page] || 0).to_i
    @post = Post.new
    @project = Project.find params[:id]

    exist = @project.posts.
              offset(POST_SIZE * (page+1)).limit(1).count > 0
    @posts = @project.posts.
              offset(POST_SIZE * page).limit(POST_SIZE)

    respond_to do |format|
      format.html
      format.json { render json: { posts: @posts.as_json(
        include: { user: { only: :name }, project: { only: :name } }),
        more_exist: exist } }
    end
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/admin/projects/_form_error_messages.html.erb
<% if @project.errors.any? %>
  <div class="alert alert-danger col-md-8 col-md-offset-2">
    <h3><%= pluralize(@project.errors.count, "error") %> prohibited this request from being sent:</h3>

    <ul>
    <% @project.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/projects/_search_toggle.html.erb
<div class="box-margin">
  <h3>
    Members
    <span class="label label-primary">
      {{ results.length }}
    </span>
    <span class="pull-right">
        <button data-toggle="collapse" data-target="#search_users"
          class="btn btn-default">
          <span id="search-icon" class="glyphicon glyphicon-off"></span>
        </button>
    </span>
  </h3>
</div><hr />

app/views/admin/projects/_table.html.erb
  <table class="table table-hover" ng-init="init_results(project)">
    <thead>
      <tr>
        <th></th>
        <th>Name</th>
        <th>Email</th>
        <th>Phone</th>
        <th>In Project</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <tr ng-repeat="user in results">
        <td style="width: 52px;"><%= image_tag("image.jpg",
                  class: "img-circle") %></td>
        <td>{{ user.name }}</td>
        <td>{{ user.email }}</td>
        <td>{{ user.phone }}</td>
        <td style="text-align: center; width: 81px;">{{ user.projects.length }}</td>
        <td>
          <button class="btn btn-danger btn-circle pull-right" type="button"
            ng-click="remove(user, project)">✘</td>
        </td>
      </tr>
    </tbody>

  </table>

app/views/admin/projects/edit.html.erb
  <%= render 'admin/projects/form_error_messages' %>

  <div id="div-project-data" data-project-id="<%= @project.id %>">
    <div class="col-md-6 col-md-push-6 content">
      <h3>Edit</h2>


        <%= form_for(@project, url: admin_project_url(@project), html: { multipart: true }) do |f| %>

          <div class="form-group">
            <%= f.label :name %><br />
            <%= f.text_field :name, autofocus: true, class: "form-control" %>
          </div>

          <div class="form-group">
            <%= f.label :description %><br />
            <%= f.text_area :description, rows: 15, autofocus: true, class: "form-control description" %>
          </div>

          <div class="form-group">
            <%= f.label :attachment, "File attachment" %><br>
            <span class="btn btn-default btn-file">
              <%= f.file_field :file %>
            </span>
          </div>


          <%= f.submit "Submit", class: "btn btn-primary btn-lg" %><br /><br />
        <% end %>




    </div>
    <div class="col-md-6 col-md-pull-6">
      <%= render 'admin/projects/search_toggle' %>
      <div id="search_users" class="collapse in">
        <%= render 'users/search_users' %>
      </div>

      <div ng-show="results.length > 0">
        <%= render 'admin/projects/table' %>
      </div>

      <div ng-hide="results.length > 0">
        <%= render 'users/empty_label' %>
      </div>
    </div>
  </div>

app/views/admin/projects/index.html.erb
<%= render 'projects/project' %>

app/views/admin/projects/new.html.erb
  <%= render 'admin/projects/form_error_messages' %>

<div class="jumbotron container container-fluid col-md-8 col-md-offset-2">
  <h2>Project</h2>


  <%= form_for(@project, url: admin_projects_url(@project), html: { multipart: true }) do |f| %>

    <div class="form-group">
      <%= f.label :name %><br />
      <%= f.text_field :name, autofocus: true, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= f.label :description %><br />
      <%= f.text_area :description, rows: 15, autofocus: true, class: "form-control description" %>
    </div>

    <div class="form-group">
      <%= f.label :attachment, "File attachment" %><br>
      <span class="btn btn-default btn-file">
        <%= f.file_field :file %>
      </span>
    </div>


    <%= f.submit "Submit", class: "btn btn-primary btn-lg" %><br /><br />
  <% end %>



</div>

app/views/admin/projects/show.html.erb
<div id="div-project-data" data-project-id="<%= @project.id %>">
  <div class="col-md-6 col-md-push-6 text-center content">

    <%= render 'projects/content' %>

  </div>
  <div class="col-md-6 col-md-pull-6">
    <%= render 'admin/projects/search_toggle' %>
    <div id="search_users" class="collapse in">
      <%= render 'users/search_users' %>
    </div>

    <div ng-show="results.length > 0">
      <%= render 'admin/projects/table' %>
    </div>

    <div ng-hide="results.length > 0">
      <%= render 'users/empty_label' %>
    </div>
  </div>
</div>