config/routes.rb
Rails.application.routes.draw do
  get    'dashboard'           => 'dashboard#index'
  get    'join'                => 'join#new'
  post   'join'                => 'join#create'

  get    'slack'               => 'slack#new'
  post   'slack'               => 'slack#notifier'

  resources :comments, only: [:create]

  resources :request_acceptants, only: [:edit]

  get    'posts/:id/comments'  => 'posts#comments'
  resources :posts, only: [:create, :destroy]

  namespace :admin do
    get    'projects/list_users' => 'projects#list_users'
    post   'projects/add'        => 'projects#add'
    post   'projects/pdf'        => 'projects#pdf'
    delete 'projects/remove'     => 'projects#remove'
    resources :projects

    resources :requests, only: [:index, :create, :destroy]
    post 'requests/pdf'    => 'requests#pdf'
    get 'requests/sent'    => 'requests#sent'
    get 'requests/pending' => 'requests#pending'
  end

  resources :projects, only: [:index, :show]

  devise_for :users, controllers: { registrations: 'users/registrations' }

  resources :users

  authenticated :user do
    root :to => 'dashboard#index', :as => :authenticated_root
  end
  root 'homepage#index'

  match '*path', to: 'errors#routing', via: [:get]
end

app/models/project.rb
class Project < ActiveRecord::Base
  has_many :relationships, foreign_key: "project_id",
                           dependent:   :destroy

  has_many :users, through: :relationships,  source: :user
  has_many :posts, dependent: :destroy

  mount_uploader :file, FileUploader

  validates :name, presence: true
  validates :description, presence: true
end

app/controllers/admin/projects_controller.rb
class Admin::ProjectsController < Admin::ApplicationController

  def index
    @projects = Project.all
  end

  def new
    @project = Project.new
  end

  def edit
    @project = Project.find params[:id]
  end

  def update
    @project = Project.find params[:id]
    if @project.update_attributes(project_params)
      redirect_to admin_project_url(@project), notice: "Project updated!"
    else
      redirect_to admin_project_url(@project), alert: "Something wrong, please try again."
    end
  end

  def create
    @project = Project.new project_params
    if @project.save
      flash[:success] = "Request sent!"
      redirect_to root_url
    else
      render :new
    end
  end

  def show
    begin
      @project = Project.find params[:id]
      page = (params[:page] || 0).to_i
      find_users page
      respond_to do |format|
          format.html { render :show }
      end
    rescue
      redirect_to root_url
    end
  end

  def add
    user = User.find params[:user_id]
    project = Project.find params[:project_id]

    user.relationships.create project_id: project.id

    @results = project.users

    respond_to do |format|
        format.html
        format.json { render json: @results.to_json(
          include: { projects: { only: :id } }) }
    end
  end

  def remove
    user = User.find params[:user_id]
    project = Project.find params[:project_id]

    user.relationships.find_by_project_id(project.id).destroy

    @results = project.users

    respond_to do |format|
        format.html
        format.json { render json: @results.to_json(
          include: { projects: { only: :id } }) }
    end
  end

  def list_users
    project = Project.find params[:project_id]
    @results = project.users

    respond_to do |format|
        format.html
        format.json { render json: @results.to_json(
          include: { projects: { only: :id } }) }
    end
  end

  def pdf
    project = Project.find(params[:format])

    # File location
    location = project.file.file.file
    filename = "project_" + project.id.to_s + "_attachment.pdf"

    send_file(location, :filename => filename, :type => "application/pdf")
  end

  private
  def project_params
    request = params.require(:project).permit(:name, :description, :file)
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

  def index
    @projects = current_user.projects
  end

  def show
    page = (params[:page] || 0).to_i
    @post = Post.new
    @project = Project.find params[:id]

    exist = @project.posts.
              offset(POST_SIZE * (page+1)).limit(1).count > 0
    @posts = @project.posts.
              offset(POST_SIZE * page).limit(POST_SIZE)

    respond_to do |format|
      format.html
      format.json { render json: { posts: @posts.as_json(
        include: { user: { only: :name }, project: { only: :name } }),
        more_exist: exist } }
    end
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_content.html.erb
<div class="container-fluid content_margin">
  <div class="header-div">
    <div class="header-center"><h3><%= @project.name %></h3></div>


      <div class="header-right row">
        <% if current_user.user_type.user_type.eql? UserType::Admin%>
        <div class="col-md-6">
          <%= link_to edit_admin_project_url(@project), class: 'btn btn-default' do %>
            <span class="glyphicon glyphicon-edit"></span>
          <% end %>
        </div>
        <% end %>
        <div class="col-md-6">
          <button data-toggle="collapse" data-target="#project_content"
            class="btn btn-default">
            <span id="search-icon" class="glyphicon glyphicon-off"></span>
          </button>
        </div>
      </div>


  </div>
  <hr />
  <div id="project_content" class="collapse in">

    <p class="show_content"><%= @project.description %></p>
    <hr />
    <% if @project.file.present? %>
      <%= link_to 'Attachment', admin_projects_pdf_url(@project), method: :post,
                class: 'btn btn-default attachment' %>
    <% else %>
      <button class="btn btn-default attachment disabled">
        No Attachment Available
      </button>
    <% end %>
  </div>
</div>

app/views/projects/_project.html.erb
<ol class="list-group">
  <% @projects.each do |project| %>
    <div class="col-md-4 box_margin">
      <div class="list-group-item text-center result_box">
        <div class="content_header">
          <h3>
            <%= link_to project.name, (admin? ? admin_project_url(project) : project_url(project)) %>
            <br /><hr /></h3>
        </div>
        <div class="content_mid line-clamp">
          <p><%= project.description %></p>
        </div>
        <div>
          <% if project.file.present? %>
            <%= link_to 'Attachment', admin_projects_pdf_url(project), method: :post,
                      class: 'btn btn-default attachment' %>
          <% else %>
            <button class="btn btn-default attachment disabled">
              No Attachment Available
            </button>
          <% end %>
        </div>
      </div>
    </div>
  <% end %>
</ol>

app/views/projects/index.html.erb
<%= render 'projects/project' %>

app/views/projects/show.html.erb
<div class="col-md-6 col-md-push-6">
  <%= render 'projects/content' %>
</div>


<div class="col-md-6 col-md-pull-6" ng-controller="PostsController"
  id="div-project-data" data-project-id="<%= @project.id %>">

  <div class="form-post">
    <form name="postForm">
      <div class="form-group">

        <textarea class="form-control postAutoExpand input-expand" name="content"
          ng-model="content" data-min-rows="2" rows="2" autofocus="true"></textarea>
        <div class="row" style="margin-top: 10px;">
          <div class="form-group col-md-6">
            <span class="btn btn-default btn-file">
              <input name="file" fileread="file" ng-model="file" type="file"></input>
            </span>
          </div>
          <div class="col-md-6 div-post">
            <button class="btn btn-primary btn-post" type="button"
              ng-click="post(content, file, project); content=''">
               POST
             </button>
          </div>
        </div>
      </div>
    </form>
  </div>

  <hr />

  <div ng-init="more_func(project)">
    <div ng-repeat="post in posts">
      <%= render 'posts/post' %>
    </div>
  </div>

  <%= render 'posts/more_button' %>

  <%= render 'posts/nothing' %>


</div>