config/routes.rb
Rails.application.routes.draw do
  get    'dashboard'           => 'dashboard#index'
  get    'join'                => 'join#new'
  post   'join'                => 'join#create'

  get    'slack'               => 'slack#new'
  post   'slack'               => 'slack#notifier'

  resources :comments, only: [:create]

  resources :request_acceptants, only: [:edit]

  get    'posts/:id/comments'  => 'posts#comments'
  resources :posts, only: [:create, :destroy]

  namespace :admin do
    get    'projects/list_users' => 'projects#list_users'
    post   'projects/add'        => 'projects#add'
    post   'projects/pdf'        => 'projects#pdf'
    delete 'projects/remove'     => 'projects#remove'
    resources :projects

    resources :requests, only: [:index, :create, :destroy]
    post 'requests/pdf'    => 'requests#pdf'
    get 'requests/sent'    => 'requests#sent'
    get 'requests/pending' => 'requests#pending'
  end

  resources :projects, only: [:index, :show]

  devise_for :users, controllers: { registrations: 'users/registrations' }

  resources :users

  authenticated :user do
    root :to => 'dashboard#index', :as => :authenticated_root
  end
  root 'homepage#index'

  match '*path', to: 'errors#routing', via: [:get]
end

app/models/request.rb
class Request < ActiveRecord::Base
  attr_accessor :acceptant_token

  belongs_to :user_type

  mount_uploader :file, FileUploader

  validates :name, presence: true
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, :presence => true, :length => { maximum: 255 },
                    :format => { with: VALID_EMAIL_REGEX },
                    :uniqueness => { case_sensitive: false }
  validates :phone, :presence => true
  validates :user_type, :presence => true
  validate :file_exist


  # Returns the hash digest of the given string.
  def Request.digest string
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create string, cost: cost
  end

  # Returns a random token.
  def Request.new_token
    SecureRandom.urlsafe_base64
  end

  # Accepts a user request in the database for sing up
  def accept
    update_columns :accepted => true, :accepted_at => Time.zone.now
  end

  # Returns true if the given token matches the digest
  def authenticated? acceptant_token
    BCrypt::Password.new(acceptant_digest).is_password? acceptant_token
  end

  # Creates and assigns the acceptant token and digest
  def create_acceptant_digest
    self.acceptant_token = Request.new_token
    update_columns acceptant_digest: Request.digest(acceptant_token)
  end

  # Sends activatation email.
  def send_acceptant_email
    UserMailer.request_acceptant(self).deliver_now
  end

  private

    def file_exist
      unless file.present?
        errors.add(:file, "cannot be null")
      end
    end
end

app/controllers/admin/requests_controller.rb
class Admin::RequestsController < Admin::ApplicationController


  def index
    @requests_pending = Request.where(accepted: false).
                                paginate(page: params[:pending_page], per_page: 5)
    @requests_sent    = Request.where(accepted: true).
                                paginate(page: params[:page_sent], per_page: 2)
  end

  def sent
    if params[:filter]
      user_type_id = UserType.find_by_user_type(params[:filter]).id
      @requests = Request.where(accepted: true, user_type_id: user_type_id).
                                paginate(page: params[:page], per_page: 10)
    else
      @requests = Request.where(accepted: true).
                                paginate(page: params[:page], per_page: 10)
    end
  end

  def pending
    if params[:filter]
      user_type_id = UserType.find_by_user_type(params[:filter]).id
      @requests = Request.where(accepted: false, user_type_id: user_type_id).
                                paginate(page: params[:page], per_page: 10)
    else
      @requests = Request.where(accepted: false).
                                paginate(page: params[:page], per_page: 10)
    end
  end

  def create
    @request = Request.find params[:format]
    if @request
      @request.create_acceptant_digest
      @request.send_acceptant_email
      @request.accept
      @requests = Request.all
      redirect_to request.referer, notice: "Email sent"
    else
      redirect_to request.referer, alert: "Somthing wrong"
    end
  end

  def destroy
    Request.find(params[:id]).destroy

    @requests = Request.all
    redirect_to request.referer, notice: "User deleted"
  end

  def pdf
    request = Request.find(params[:format])

    # File location
    location = request.file.file.file
    filename = "request_" + request.id.to_s + "_attachment.pdf"

    send_file(location, :filename => filename, :type => "application/pdf")
  end
end

app/views/admin/requests/_filter.html.erb
<div>
  <% if current_page?(admin_requests_pending_path) %>
    <span class="text-muted">Filter by role: </span>
    <% UserType.all.each do |user_type| %>
      <% if user_type.user_type.eql? params[:filter] %>
        <%= link_to user_type.user_type, admin_requests_pending_path(filter: user_type.user_type),
              class: 'btn btn-primary btn-xs'%>
      <% else %>
        <%= link_to user_type.user_type, admin_requests_pending_path(filter: user_type.user_type),
              class: 'btn btn-default btn-xs'%>
      <% end %>
    <% end %>
    <% if params[:filter] %>
      <span> | <span>
      <%= link_to 'Reset Filter', admin_requests_pending_path,
            class: 'btn btn-danger btn-xs'%>
    <% end %>
  <% elsif current_page?(admin_requests_sent_path) %>
    <span class="text-muted">Filter by role: </span>
    <% UserType.all.each do |user_type| %>
      <% if user_type.user_type.eql? params[:filter] %>
        <%= link_to user_type.user_type, admin_requests_sent_path(filter: user_type.user_type),
              class: 'btn btn-primary btn-xs'%>
      <% else %>
        <%= link_to user_type.user_type, admin_requests_sent_path(filter: user_type.user_type),
              class: 'btn btn-default btn-xs'%>
      <% end %>
    <% end %>
    <% if params[:filter] %>
      <span> | <span>
      <%= link_to 'Reset Filter', admin_requests_sent_path,
            class: 'btn btn-danger btn-xs'%>
    <% end %>
  <% end %>
</div>

app/views/admin/requests/_left_nav.html.erb
  <div class="col-md-2" id="left-nav">
    <div class="sidebar-nav">
      <div class="navbar navbar-default" role="navigation">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".sidebar-navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <span class="visible-xs navbar-brand">Sidebar menu</span>
        </div>
        <div class="navbar-collapse collapse sidebar-navbar-collapse">
          <ul class="nav navbar-nav">
            <li class="<%= 'active' if current_page?(admin_requests_pending_path) %>">
              <%= link_to 'Pending Requests', admin_requests_pending_url, method: :get %>
            </li>
            <li class="<%= 'active' if current_page?(admin_requests_sent_path) %>">
              <%= link_to 'Sent Requests', admin_requests_sent_url, method: :get %>
            </li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </div>
  </div>

app/views/admin/requests/_request.html.erb
  <tbody>
    <tr>
      <td><%= request.name %></td>
      <td><%= request.email %></td>
      <td><%= request.phone %></td>
      <td><%= request.user_type.user_type %></td>
      <td>
          <%= link_to admin_requests_pdf_path(request), method: :post,
                class: 'btn btn-default btn-sm' do %>
            <i class="glyphicon glyphicon-open-file"></i>
          <% end %>
      </td>
      <td><%= request.created_at.strftime("%a %d %b %I:%M:%S %p") %></td>
      <% unless request.accepted? %>
      <td>
        <%= link_to admin_requests_path(request), method: :post,
              class: "btn btn-success btn-sm", data: { confirm: "You sure?" } do %>
          <i class="glyphicon glyphicon-ok"></i>
        <% end %>
        <%= link_to admin_request_path(request), method: :delete,
              class: "btn btn-danger btn-sm", data: { confirm: "You sure?" } do %>
          <i class="glyphicon glyphicon-remove"></i>
        <% end %>
      </td>
      <% else %>
      <td>
        <%= link_to "Resend Email", admin_requests_path(request), method: :post,
          class: "btn btn-warning", data: { confirm: "You sure?" } %>
      </td>
      <% end %>
    </tr>
  </tbody>

app/views/admin/requests/_table.html.erb
<div class="row">
  <%= render 'admin/requests/left_nav' %>
  <div class="col-md-10">
    <div class="panel panel-default">
      <div class="panel-heading">
        <span class="h3">
          <% if current_page? admin_requests_pending_url %>
            Pending Requests
          <% else %>
            Sent Requests
          <% end %>
          <span class="label label-info">
            <%= @requests.count %>
          </span>
        </span>
      </div>
      <div class="panel-body">
        <%= render 'admin/requests/filter' %>
      </div>
      <table class="table table-hover">
        <thead>
          <tr>
            <th>Name</th>
            <th>Email</th>
            <th>Phone</th>
            <th>Role</th>
            <th>File</th>
            <th>Sent on</th>
            <th>Action</th>
          </tr>
        </thead>
          <%= render @requests %>
      </table>

    </div>
    <%= will_paginate @requests %>
  </div>
</div>

app/views/admin/requests/index.html.erb
<ul class="nav nav-tabs">
  <li class="active"><a data-toggle="tab" href="#menu1">Menu 1</a></li>
  <li><a data-toggle="tab" href="#menu2">Menu 2</a></li>
</ul>

<div class="tab-content">
  <div id="menu1" class="tab-pane fade in active">
    <%= will_paginate @requests_pending, param_name: 'pending_page' %>
    <table class="table table-striped">
      <thead>
        <tr>
          <th>Name</th>
          <th>Email</th>
          <th>Phone</th>
          <th>File</th>
          <th>Action</th>
        </tr>
      </thead>
      <tbody>
        <%= render @requests_pending %>
      </tbody>
    </table>
  </div>
  <div id="menu2" class="tab-pane fade">
    <%= will_paginate @requests_sent, param_name: 'page_sent' %>
    <table class="table table-striped">
      <thead>
        <tr>
          <th>Name</th>
          <th>Email</th>
          <th>Phone</th>
          <th>File</th>
          <th>Action</th>
        </tr>
      </thead>
      <tbody>
        <%= render @requests_sent %>
      </tbody>
    </table>
  </div>
</div>

app/views/admin/requests/pending.html.erb
<%= render 'admin/requests/table' %>

app/views/admin/requests/sent.html.erb
<%= render 'admin/requests/table' %>